/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three";

export function Character({ animation, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/assets/models/Player_1_pose.glb",
  );

  Object.values(materials).forEach((material) => (material.depthWrite = true));
  materials.OUJI_D_face_alpha.transparent = false;
  materials.OUJI_D_face_alpha.alphaTest = 0.5;

  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions[animation]?.reset().fadeIn(0.24).play();
    return () => actions?.[animation]?.fadeOut(0.24);
  }, [animation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="OUJI60_D" scale={0.02} rotation={[Math.PI / 2, 0, 0]}>
          <group name="OUJI60_D001">
            <group name="model">
              <skinnedMesh
                name="antena_m"
                geometry={nodes.antena_m.geometry}
                material={materials.OUJI60_D}
                skeleton={nodes.antena_m.skeleton}
              />
              <skinnedMesh
                name="body_m"
                geometry={nodes.body_m.geometry}
                material={materials.OUJI60_D}
                skeleton={nodes.body_m.skeleton}
              />
              <group name="body_root" />
              <skinnedMesh
                name="cheak_01_m"
                geometry={nodes.cheak_01_m.geometry}
                material={materials.OUJI_D_face_alpha}
                skeleton={nodes.cheak_01_m.skeleton}
              />
              <skinnedMesh
                name="eye_01_m"
                geometry={nodes.eye_01_m.geometry}
                material={materials.OUJI_D_face_alpha}
                skeleton={nodes.eye_01_m.skeleton}
              />
              <skinnedMesh
                name="face_01_m"
                geometry={nodes.face_01_m.geometry}
                material={materials.OUJI60_D}
                skeleton={nodes.face_01_m.skeleton}
              />
              <group name="face_root">
                <group name="eye">
                  <group name="eye_01" />
                  <group name="eye_02" />
                  <group name="eye_03" />
                  <group name="eye_04" />
                  <group name="eye_05" />
                </group>
                <group name="face">
                  <group name="face_01" />
                  <group name="face_02" />
                  <group name="face_03" />
                </group>
                <group name="mouth">
                  <group name="mouth_01" />
                  <group name="mouth_02" />
                  <group name="mouth_03" />
                  <group name="mouth_04" />
                  <group name="mouth_05" />
                  <group name="mouth_06" />
                  <group name="mouth_07" />
                  <group name="mouth_08" />
                  <group name="mouth_09" />
                  <group name="mouth_10" />
                  <group name="mouth_11" />
                </group>
                <group name="parts">
                  <group name="angry_01" />
                  <group name="cheak_01" />
                  <group name="shock_01" />
                  <group name="tear_01" />
                </group>
              </group>
              <skinnedMesh
                name="hand_L_m"
                geometry={nodes.hand_L_m.geometry}
                material={materials.OUJI60_D}
                skeleton={nodes.hand_L_m.skeleton}
              />
              <skinnedMesh
                name="hand_R_m"
                geometry={nodes.hand_R_m.geometry}
                material={materials.OUJI60_D}
                skeleton={nodes.hand_R_m.skeleton}
              />
              <skinnedMesh
                name="head_m"
                geometry={nodes.head_m.geometry}
                material={materials.OUJI60_D}
                skeleton={nodes.head_m.skeleton}
              />
              <skinnedMesh
                name="leg_L_m"
                geometry={nodes.leg_L_m.geometry}
                material={materials.OUJI60_D}
                skeleton={nodes.leg_L_m.skeleton}
              />
              <skinnedMesh
                name="leg_R_m"
                geometry={nodes.leg_R_m.geometry}
                material={materials.OUJI60_D}
                skeleton={nodes.leg_R_m.skeleton}
              />
              <skinnedMesh
                name="mouth_01_m"
                geometry={nodes.mouth_01_m.geometry}
                material={materials.OUJI_D_face_alpha}
                skeleton={nodes.mouth_01_m.skeleton}
              />
              <skinnedMesh
                name="nose_m"
                geometry={nodes.nose_m.geometry}
                material={materials.OUJI60_D}
                skeleton={nodes.nose_m.skeleton}
              />
              <primitive object={nodes.JNT_root} />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/Player_1_pose.glb");
